# Generated by Django 5.0.6 on 2024-10-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopjewelry", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
